/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import day1.Vault
import day2.AnomalyDetection

class App {}

fun main() {
    val day2 = AnomalyDetection()
    day2.solve("./src/main/kotlin/day2/input.txt")
}
