/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import day3.Batteries

class App

fun main() {
  val day3 = Batteries("./src/main/kotlin/day3/input.txt")
  val result = day3.solve()

  print(result)
}
