/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import day3.Batteries
import day4.PaperGrid

class App

fun main() {
  val day4 = PaperGrid("./src/main/kotlin/day4/input.txt")
  val result = day4.solve()

  print(result)
}
